### ISSUE TITLE
Linux deprecated literal operator

### ISSUE THREAD

**Issue by TomBursch** [juliansteenbakker/flutter_secure_storage#920]
On the latest fedora version, I get the following errors:

```
project/linux/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_linux/linux/include/json.hpp:24392:35: error: identifier '_json' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
project/linux/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_linux/linux/include/json.hpp:24400:49: error: identifier '_json_pointer' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
project/linux/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_linux/linux/include/json.hpp:24464:58: error: identifier '_json' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
project/linux/flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_linux/linux/include/json.hpp:24465:58: error: identifier '_json_pointer' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
Error: Build process failed
```

Using flutter_secure_storage 9.2.4 and flutter_secure_storage_linux 1.2.2

If I remove the spaces around the string literal, the app compiles again.

**Comment by lordvcs** [comment]
I am encountering this on my ubuntu 25 too

**Comment by m-berto** [comment]
Same issue after upgrading to Fedora 42

**Comment by krille-chan** [comment]
As a workaround until is https://github.com/juliansteenbakker/flutter_secure_storage/pull/923 merged, those two overrides fixes it for me on Ubuntu 25.04:

```yaml
dependency_overrides:
  flutter_secure_storage_linux:
    git:
      url: https://github.com/m-berto/flutter_secure_storage.git
      ref: patch-2
      path: flutter_secure_storage_linux
  flutter_secure_storage_platform_interface: 2.0.0
```
